test_that("assert_env_name works!", {
  expect_no_error(assert_env_name("REDCapSync"))
  expect_no_error(assert_env_name("REDCap_Sync"))
  expect_no_error(assert_env_name("my_form"))
  expect_no_error(assert_env_name("a"))
  expect_no_error(assert_env_name("A"))
  expect_error(assert_env_name("1A"))
  expect_error(assert_env_name("My Form"))
  expect_error(assert_env_name("my-form"))
  expect_error(assert_env_name("varName!"))
  expect_error(assert_env_name("_form"))
  expect_no_error(assert_env_name("ABCD", max.chars = 4))
  expect_error(assert_env_name("ABCDE", max.chars = 4))
  expect_error(assert_env_name("_ABCD", underscore_allowed_first = FALSE))
  expect_no_error(assert_env_name("_ABCD", underscore_allowed_first = TRUE))
})
test_that("split_choices works!", {
  choices <- split_choices("1, one | 2, two")
  checkmate::expect_data_frame(choices, nrows = 2, ncols = 2)
  expect_false(anyNA(choices$code))
  expect_false(anyNA(choices$name))
  expect_true(choices$code[[1]]=="1")
  expect_true(choices$code[[2]]=="2")
  expect_true(choices$name[[1]]=="one")
  expect_true(choices$name[[2]]=="two")
  expect_error(split_choices("1. one | 2, two"))
  choices <- split_choices("1, one even with , second comma | 2, two")
  checkmate::expect_data_frame(choices, nrows = 2, ncols = 2)
  expect_false(anyNA(choices$code))
  expect_false(anyNA(choices$name))
})
test_that("split_choices works if space missing!", {
  choices <- split_choices("1,one | 2,two")
  checkmate::expect_data_frame(choices, nrows = 2, ncols = 2)
  expect_false(anyNA(choices$code))
  expect_false(anyNA(choices$name))
})
