#test-utils-RosyUtils ==========================================================
test_that("assert_env_name works!", {
  expect_no_error(assert_env_name("REDCapSync"))
  expect_no_error(assert_env_name("REDCap_Sync"))
  expect_no_error(assert_env_name("my_form"))
  expect_no_error(assert_env_name("a"))
  expect_no_error(assert_env_name("A"))
  expect_error(assert_env_name("1A"))
  expect_error(assert_env_name("My Form"))
  expect_error(assert_env_name("my-form"))
  expect_error(assert_env_name("varName!"))
  expect_error(assert_env_name("_form"))
  expect_no_error(assert_env_name("ABCD",max.chars = 4))
  expect_error(assert_env_name("ABCDE",max.chars = 4))
  expect_error(assert_env_name("_ABCD",underscore_allowed_first = FALSE))
  expect_no_error(assert_env_name("_ABCD",underscore_allowed_first = TRUE))
})
