#' @keywords internal
"_PACKAGE"
## usethis namespace: start
#' @importFrom checkmate makeAssertCollection
#' @importFrom checkmate assert_choice
#' @importFrom checkmate assert_date
#' @importFrom checkmate assert_date
#' @importFrom checkmate assert_character
#' @importFrom checkmate assert_logical
#' @importFrom checkmate assert_list
#' @importFrom checkmate assert_string
#' @importFrom checkmate assert_integerish
#' @importFrom checkmate assert_names
#' @importFrom checkmate assert_posixct
#' @importFrom checkmate assert_data_frame
#' @importFrom checkmate assert_tibble
#' @importFrom checkmate assert_path_for_output
#' @importFrom checkmate assert_true
#' @importFrom checkmate assert_class
#' @importFrom checkmate assert_directory
#' @importFrom checkmate assert_directory_exists
#' @importFrom checkmate assert_set_equal
#' @importFrom checkmate check_set_equal
#' @importFrom checkmate check_true
#' @importFrom cli cli_abort
#' @importFrom cli cli_alert_danger
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_alert_warning
#' @importFrom dplyr bind_rows
#' @importFrom dplyr first
#' @importFrom dplyr last
#' @importFrom dplyr starts_with
#' @importFrom dplyr select
#' @importFrom dplyr tibble
#' @importFrom dplyr as_tibble
#' @importFrom dplyr pull
#' @importFrom dplyr filter
#' @importFrom redcapAPI REDCAP_METADATA_FIELDTYPE
#' @importFrom redcapAPI REDCAP_METADATA_VALIDATION_TYPE
#' @importFrom redcapAPI REDCAP_PROJECT_PURPOSE
#' @importFrom redcapAPI REDCAP_SYSTEM_FIELDS
#' @importFrom REDCapR sanitize_token
#' @importFrom rlang current_call
#' @importFrom R6 R6Class
## usethis namespace: end
NULL
